version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sfa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smart_feedback_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - sfa_pgdata:/var/lib/postgresql/data

volumes:
  sfa_pgdata:
